# Generated by Django 3.2 on 2021-04-26 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of album', max_length=200)),
                ('released', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a song genre (e.g. hip-hop, rock, alternative, techno etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lyrics', models.TextField(help_text='Enter some lyrics.', max_length=10000)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.album')),
                ('author', models.ForeignKey(default='unknown', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author')),
                ('genre', models.ForeignKey(help_text='Enter genres of the song.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre')),
            ],
        ),
        migrations.CreateModel(
            name='SongInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this composition of art.', primary_key=True, serialize=False)),
                ('number_of_listens', models.IntegerField(default=0)),
                ('released', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('s', 'Coming out soon'), ('r', 'Removed from public access'), ('a', 'Available'), ('d', 'Disabled in this region')], default='s', help_text='Status for the song', max_length=1)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.song')),
            ],
            options={
                'ordering': ['-number_of_listens'],
            },
        ),
    ]
