# Generated by Django 3.1.7 on 2021-05-01 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'permissions': (('can_add_songs', 'can_manage_collection'),)},
        ),
        migrations.RemoveField(
            model_name='songinstance',
            name='released',
        ),
        migrations.AddField(
            model_name='songinstance',
            name='bought',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 21, 5, 40, 407952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
