# Generated by Django 3.2 on 2021-05-03 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210503_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('can_view_profile', 'May have a profile')]},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['author'], 'permissions': (('can_append_songs', 'Can_manage_collection'),)},
        ),
        migrations.AlterField(
            model_name='songinstance',
            name='bought',
            field=models.DateField(default=datetime.datetime(2021, 5, 3, 8, 42, 14, 503973, tzinfo=utc)),
        ),
    ]
